-- ============================================
-- PLACE APP - SETUP DO BANCO DE DADOS
-- Execute este script no SQL Editor do Supabase
-- ============================================

-- ============================================
-- LIMPEZA (caso já existam dados)
-- ============================================
-- IMPORTANTE: Deletar na ordem correta por causa das Foreign Keys

-- Deletar função primeiro (se existir)
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- Deletar tabelas (CASCADE remove automaticamente triggers, policies, etc)
DROP TABLE IF EXISTS lesson_links CASCADE;
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- ============================================
-- CRIAÇÃO DAS TABELAS
-- ============================================

-- 1. Criar tabela de perfis
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  plan_type TEXT DEFAULT 'Gratuito',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criar tabela de áreas
CREATE TABLE areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  "order" INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Criar tabela de módulos
CREATE TABLE modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  thumbnail_url TEXT,
  area_id BIGINT REFERENCES areas(id) ON DELETE SET NULL,
  plan_access TEXT DEFAULT 'Gratuito',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Criar tabela de aulas
CREATE TABLE lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description_content TEXT,
  video_url TEXT,
  module_id BIGINT REFERENCES modules(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Criar tabela de links das aulas
CREATE TABLE lesson_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  url TEXT NOT NULL,
  lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- DADOS DE EXEMPLO
-- ============================================

-- Inserir áreas de exemplo
INSERT INTO areas (title, description, "order") VALUES
('Marcas Virais', 'Escolha sua marca para se conectar', 1),
('Start', 'Entenda como usar o App', 2),
('Mulher de Influência', 'Espaço para inspirar, apoiar e fortalecer.', 3),
('Study', 'Eleve ainda mais o seu nível', 4),
('Extra', 'Incentivos melhores e ganhos maiores', 5),
('Encontros ao Vivo', 'Reveja nossos momentos juntos', 6);

-- Inserir módulos de exemplo
INSERT INTO modules (title, description, area_id, plan_access) VALUES
('Como funciona o GloowApp?', 'Nesse módulo você irá descobrir, como tudo irá funcionar.', 1, 'Gratuito'),
('Ganhando seguidores no automático', 'Não pule se quiser ter resultado!', 1, 'Gratuito'),
('PressFit - Cinta Modeladora', 'Chegou a grande hora!', 1, 'Gratuito'),
('Se tornando um Creator Pro', 'Chegou a hora de começar sua história na internet', 1, 'Premium'),
('Ganhe com o TikTok Shop', 'Aqui você irá aprender como criar uma conta do zero, ganhar seguidores e bater os requisitos rapidamente para faturar muito com a TikTok Shop.', 1, 'Premium'),
('Chega de Coach', 'Preparando a sua mente.', 1, 'Premium');

-- Pegar o ID do primeiro módulo para inserir aulas
DO $$
DECLARE
  v_module_id BIGINT;
  v_lesson_id BIGINT;
BEGIN
  -- Pegar o ID do módulo "PressFit"
  SELECT id INTO v_module_id FROM modules WHERE title = 'PressFit - Cinta Modeladora' LIMIT 1;
  
  IF v_module_id IS NOT NULL THEN
    -- Inserir primeira aula (com links)
    INSERT INTO lessons (title, description_content, video_url, module_id) VALUES
    (
      'Suporte Gloow',
      'Para acessar os canais abaixo: 👇 Você deve clicar em "Mostrar mais...".
SALVEM TODOS ESTES LINKS EM UM BLOCO DE NOTAS

Suporte Oficial Gloow
Instagram Oficial - GloowApp
Grupo de Membros WhatsApp
Grupo de Membros Telegram',
      'https://www.youtube.com/embed/wGeyNNacRq4',
      v_module_id
    )
    RETURNING id INTO v_lesson_id;
    
    -- Inserir links para a primeira aula
    INSERT INTO lesson_links (text, url, lesson_id) VALUES
      ('Suporte Oficial Gloow', 'https://wa.me/551192186071', v_lesson_id),
      ('Instagram Oficial - GloowApp', 'https://www.instagram.com/s', v_lesson_id),
      ('Grupo de Membros WhatsApp', 'https://chat.whatsapp.com/D', v_lesson_id),
      ('Grupo de Membros Telegram', 'https://t.me/+qJjY3k4EkV4yN', v_lesson_id);
    
    -- Inserir demais aulas (sem links)
    INSERT INTO lessons (title, description_content, video_url, module_id) VALUES
    (
      'Boas Vindas a GloowApp',
      'Seja muito bem-vindo!',
      'https://www.youtube.com/embed/wGeyNNacRq4',
      v_module_id
    ),
    (
      'Como tudo vai funcionar?',
      'Explicando como vai funcionar.',
      'https://www.youtube.com/embed/wGeyNNacRq4',
      v_module_id
    );
  END IF;
END $$;

-- ============================================
-- POLÍTICAS RLS (Row Level Security)
-- ============================================

-- Habilitar RLS nas tabelas
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_links ENABLE ROW LEVEL SECURITY;

-- Políticas para profiles
CREATE POLICY "Usuários podem ver seu próprio perfil"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Usuários podem atualizar seu próprio perfil"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- Políticas para áreas (todos podem ler)
CREATE POLICY "Áreas são públicas para leitura"
  ON areas FOR SELECT
  TO authenticated
  USING (true);

-- Políticas para módulos (todos podem ler)
CREATE POLICY "Módulos são públicos para leitura"
  ON modules FOR SELECT
  TO authenticated
  USING (true);

-- Políticas para aulas (todos podem ler)
CREATE POLICY "Aulas são públicas para leitura"
  ON lessons FOR SELECT
  TO authenticated
  USING (true);

-- Políticas para links (todos podem ler)
CREATE POLICY "Links são públicos para leitura"
  ON lesson_links FOR SELECT
  TO authenticated
  USING (true);

-- ============================================
-- TRIGGERS PARA ATUALIZAR updated_at
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_areas_updated_at BEFORE UPDATE ON areas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_modules_updated_at BEFORE UPDATE ON modules
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_lessons_updated_at BEFORE UPDATE ON lessons
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- FIM DO SETUP
-- ============================================

-- Verificar dados inseridos
SELECT 'Áreas criadas:', COUNT(*) FROM areas;
SELECT 'Módulos criados:', COUNT(*) FROM modules;
SELECT 'Aulas criadas:', COUNT(*) FROM lessons;
SELECT 'Links criados:', COUNT(*) FROM lesson_links;

